#!/usr/bin/env python3
"""Subset FontAwesome to only the icons used on Lago Bello.

Run with the project's venv:

    venv/bin/python3 scripts/fa-subset/subset.py

Reads the source FA files in this directory (full all.css + the three woff2
font files), parses unicode codepoints from the CSS, runs pyftsubset on each
font file, and writes:

  - static/css/fa-subset.css                       (slim CSS)
  - static/webfonts/fa/fa-solid-subset.woff2
  - static/webfonts/fa/fa-brands-subset.woff2

To refresh after adding a new fa-* icon to a template:
  1. Add its name to ICONS below (and BRAND_NAMES if it's a brand glyph).
  2. Re-run this script.
  3. Commit the regenerated CSS + woff2.

Source files come from https://use.fontawesome.com/releases/v6.7.2/ — kept
here as build-time inputs and not published to the site.
"""
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent.parent
SRC_CSS = HERE / "all.css"
OUT_CSS = PROJECT / "static/css/fa-subset.css"
OUT_DIR = PROJECT / "static/webfonts/fa"
PYFT = PROJECT / "venv/bin/pyftsubset"

ICONS = [
    "fa-align-justify", "fa-apple", "fa-arrows-alt", "fa-bolt", "fa-calendar", "fa-cube",
    "fa-envelope", "fa-external-link", "fa-facebook", "fa-facebook-f",
    "fa-file-alt", "fa-github", "fa-home", "fa-house-chimney", "fa-info-circle",
    "fa-instagram", "fa-lightbulb", "fa-link", "fa-linkedin-in",
    "fa-location-arrow", "fa-map-location-dot", "fa-map-marker",
    "fa-map-marker-alt", "fa-paint-brush", "fa-phone", "fa-phone-alt",
    "fa-quote-left", "fa-route", "fa-school", "fa-search", "fa-shield-halved",
    "fa-tag", "fa-tags", "fa-user", "fa-users", "fa-water",
    "fa-waze", "fa-whatsapp", "fa-x-twitter",
]
BRAND_NAMES = {"apple", "facebook", "facebook-f", "github", "instagram",
               "linkedin-in", "waze", "whatsapp", "x-twitter"}

NEEDED = {ic[3:] for ic in ICONS}

src = SRC_CSS.read_text()
name_to_cp = {}
rule_re = re.compile(r'((?:\.fa-[a-z0-9-]+,?)+)\{--fa:"\\([0-9a-fA-F]+)"\}')
for m in rule_re.finditer(src):
    cp = int(m.group(2), 16)
    for sm in re.finditer(r'\.fa-([a-z0-9-]+)', m.group(1)):
        name_to_cp[sm.group(1)] = cp

missing = NEEDED - set(name_to_cp)
if missing:
    print(f"WARN: missing icon mappings: {sorted(missing)}", file=sys.stderr)

solid_icons = {n for n in NEEDED if n in name_to_cp and n not in BRAND_NAMES}
brand_icons = {n for n in NEEDED if n in name_to_cp and n in BRAND_NAMES}
print(f"Subsetting: solid={len(solid_icons)}, brands={len(brand_icons)}")


def codepoints_arg(names):
    return ",".join(f"U+{name_to_cp[n]:04X}" for n in sorted(names) if n in name_to_cp)


def subset(src_woff2, dst_woff2, names):
    if not names:
        return
    cmd = [
        str(PYFT), str(src_woff2),
        f"--output-file={dst_woff2}",
        f"--unicodes={codepoints_arg(names)}",
        "--flavor=woff2",
        "--with-zopfli",
        "--no-hinting",
        "--desubroutinize",
    ]
    subprocess.run(cmd, check=True)


subset(HERE / "fa-solid.woff2", OUT_DIR / "fa-solid-subset.woff2", solid_icons)
subset(HERE / "fa-brands.woff2", OUT_DIR / "fa-brands-subset.woff2", brand_icons)

parts = ["""/* Self-hosted FontAwesome subset — regenerated by scripts/fa-subset/subset.py.
   Edit ICONS in that script, re-run, commit the result. */
@font-face {
  font-family: 'Font Awesome 6 Free';
  font-style: normal;
  font-weight: 900;
  font-display: block;
  src: url('../webfonts/fa/fa-solid-subset.woff2') format('woff2');
}
@font-face {
  font-family: 'Font Awesome 6 Brands';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url('../webfonts/fa/fa-brands-subset.woff2') format('woff2');
}
.fa, .fas, .fa-solid, .far, .fa-regular, .fab, .fa-brands {
  -webkit-font-smoothing: antialiased;
  display: var(--fa-display, inline-block);
  font-style: normal;
  font-variant: normal;
  line-height: 1;
  text-rendering: auto;
}
.fa, .fas, .fa-solid, .far, .fa-regular { font-family: 'Font Awesome 6 Free'; font-weight: 900; }
.fab, .fa-brands { font-family: 'Font Awesome 6 Brands'; font-weight: 400; }
.fa::before, .fas::before, .fa-solid::before,
.far::before, .fa-regular::before,
.fab::before, .fa-brands::before,
[class^="fa-"]::before, [class*=" fa-"]::before {
  content: var(--fa);
}
"""]

for n in sorted(NEEDED):
    if n not in name_to_cp:
        continue
    parts.append(f'.fa-{n} {{ --fa: "\\{name_to_cp[n]:x}"; }}')

OUT_CSS.write_text("\n".join(parts) + "\n")
print(f"Wrote {OUT_CSS}")
